[package]
name = "fizzbuzz"
version = "0.1.0"
authors = ["KrgKo <kowpun123@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "fizzbuzz"
crate_type = ["dylib"]

[dependencies]
libc = "0.2.71"
